config/routes.rb
Rails.application.routes.draw do
  root 'login#login'

  resources :users do
    get 'change_password', on: :member
    post 'update_password', on: :member
  end

  get 'login' => 'login#login'
  get 'logout' => 'login#logout'
  post 'verify_login' => 'login#verify_login'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email, :password
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_uniqueness_of :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_user_role, except: [:login, :verify_login]

  def set_user_role
    @user = User.find_by_id(session[:user_id])
    if @user
      @role = @user.role
    else
      reset_session
      redirect_to :root
    end
  end

  def should_be_admin
    get_out unless @role == 'admin'
  end

  def should_be_admin_or_self
    get_out unless (@role == 'admin' || session[:user_id].to_s == params[:id])
  end

  def get_out
    reset_session
    flash[:notice] = "Something Fishy!!!"
    redirect_to :root
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def login

  end

  def verify_login
    @user = User.where('email= ? and password = ?', params[:email], Digest::MD5.hexdigest(params[:password])).first
    if @user
      reset_session
      session[:user_id] = @user.id
      if @user.role == "admin"
        redirect_to users_path
      else
        redirect_to user_path(@user)
      end
    else
      flash[:notice] = "Please enter valid credentials"
      redirect_to :login
    end

  end

  def logout
    reset_session
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :change_password, :update_password]
  before_action :should_be_admin, only: [:index, :new, :create]
  before_action :should_be_admin_or_self, only: [:show, :edit, :update, :change_password, :update_password,]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @user.update_column("password", Digest::MD5.hexdigest(user_params[:password]))
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_password
  end

  def update_password
    if valid_password?
      @user.update_attributes(password: Digest::MD5.hexdigest(params[:new_password]))
      redirect_to @role == "admin" ? users_path : user_path(@user)
    else
      @user.errors.add(:base, "Enter valid details.")
      render :change_password
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    if @role == 'admin'
      params.require(:user).permit(:first_name, :last_name, :email, :role, :password)
    else
      params.require(:user).permit(:first_name, :last_name, :email)
    end
  end

  def valid_password?
    (params[:new_password].blank? || (@role == 'author' && (@user.password != Digest::MD5.hexdigest(params[:old_password]) || params[:new_password] != params[:confirm_password]))) ? false : true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Security</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<br/><br/>
<%= link_to 'Logout', logout_path(session[:user_id]) if session[:user_id]%>
</body>
</html>

app/views/login/login.html.erb
<p class="flash"><%= flash[:notice] %></p>
<%= form_tag "/verify_login" do |f| %>

    <div class="field">
      Email
      <%= text_field_tag :email, nil %>
    </div>

    <div class="field">
      Password
      <%= password_field_tag :password %>
    </div>

    <div class="actions">
      <%= submit_tag "login"%>
    </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <% if @role == 'admin' %>
    <div class="field">
      <%= f.label :role %><br>
      <%= f.select :role, options_for_select([["Admin", "admin"], ["Author", "author"]], {:selected => @user.role}) %>
    </div>
    <% end %>
    <% if @user.new_record? %>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/change_password.html.erb
<%= form_tag(controller: "users" ,:action => "update_password")  do  %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%user1= User.find_by_id(session[:user_id])%>
    <%if user1.role == "admin"%>
        <div class="field">
          <%= label_tag :new_password %>
          <%= text_field_tag :new_password, nil %>
        </div>
    <%else%>
        <div class="field">
          <%= label_tag  :old_password %>
          <%= text_field_tag :old_password, nil %>
        </div>
        <div class="field">
          <%= label_tag :new_password %>
          <%= text_field_tag :new_password, nil %>
        </div>
        <div class="field">
          <%= label_tag :confirm_password %>
          <%= password_field_tag :confirm_password, nil %>
        </div>
    <%end%>
    <div class="actions">
      <%= submit_tag ("update password") %>
    </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user if @role == 'admin' %>
<%= link_to 'Back', @role == 'admin' ? users_path : user_path(@user) %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Change Password', change_password_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<% if @role == 'admin' %>
<%= link_to 'Back', users_path %>
<% else %>
<%= link_to 'Change Password', change_password_user_path(@user) %>
<% end %>